services:
  # The API Service
  - type: web
    name: brotherhood-api
    runtime: docker
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: brotherhood-db
          property: connectionString
      - key: INTERNAL_DATABASE_URL
        fromDatabase:
          name: brotherhood-db
          property: internalConnectionString
      - key: RENDER
        value: true

  # The PostgreSQL Database
databases:
  - name: brotherhood-db
    plan: free
    databaseName: brotherhood
    user: brotherhood_user
