services:
  - type: web
    name: brotherhood
    runtime: docker
    plan: free
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: brotherhood-db
          property: connectionString
      - key: RENDER
        value: true
      - key: APP_MODE
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GEMINI_API_KEY
        sync: false

  # The PostgreSQL Database
databases:
  - name: brotherhood-db
    plan: free
    databaseName: brotherhood
    user: brotherhood_user
